// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "thermostat": Application User Types
//
// Command:
// $ goagen
// --design=thermostat/design
// --out=$(GOPATH)/src/thermostat
// --version=v1.2.0-dirty

package client
