version: 2
jobs:
  build:
    docker:
      - image: yuu3/thermostat:v0.1.1
    environment:
      - GOOS: "linux"
      - GOARCH: "arm"
      - CGO_ENABLED: 1
      - CC: "arm-linux-gnueabihf-gcc-6"
    working_directory: /go/src/github.com/yuu/thermostat
    steps:
      - restore_cache:
          keys:
            - go-get

      - checkout
      - run: go get -v -d ./...
      - run: go build

      - store_artifacts:
          path: thermostat

      - save_cache:
          key: go-get
          paths:
            - /go

workflows:
  version: 2
  myworkflow:
    jobs:
      - build:

notify:
  webhooks:
    - url: $GITHUB_WEBHOOK_URL
