// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "thermostat": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/yuu/thermostat/design
// --out=$(GOPATH)/src/github.com/yuu/thermostat
// --version=v1.3.0

package app

// any thermostat info (default view)
//
// Identifier: application/json; view=default
type JSON struct {
	CurrentHeatingCoolingState int `form:"currentHeatingCoolingState" json:"currentHeatingCoolingState" xml:"currentHeatingCoolingState"`
	CurrentRelativeHumidity    int `form:"currentRelativeHumidity" json:"currentRelativeHumidity" xml:"currentRelativeHumidity"`
	CurrentTemperature         int `form:"currentTemperature" json:"currentTemperature" xml:"currentTemperature"`
	TargetHeatingCoolingState  int `form:"targetHeatingCoolingState" json:"targetHeatingCoolingState" xml:"targetHeatingCoolingState"`
	TargetRelativeHumidity     int `form:"targetRelativeHumidity" json:"targetRelativeHumidity" xml:"targetRelativeHumidity"`
	TargetTemperature          int `form:"targetTemperature" json:"targetTemperature" xml:"targetTemperature"`
}

// Validate validates the JSON media type instance.
func (mt *JSON) Validate() (err error) {

	return
}
