// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "thermostat": Application User Types
//
// Command:
// $ goagen
// --design=github.com/yuu/thermostat/design
// --out=$(GOPATH)/src/github.com/yuu/thermostat
// --version=v1.3.0

package app
